micronaut:
  application:
    name: oda-donationgoal-service
  security:
    authentication: bearer
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  executors:
    events-listener:
      type: fixed
      nThreads: 1
    command-listener:
      type: fixed
      nThreads: 1
  serde:
    serialization:
      inclusion: ALWAYS
endpoints:
  flyway:
    enabled: true
  prometheus:
    sensitive: false
  metrics:
    sensitive: false
datasources:
  default:
    schema: 'donationgoal'
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      schemas: 'donationgoal'
      default-schema: 'donationgoal'
jpa:
  default:
    entity-scan:
        packages: 'io.github.opendonationassistant'
