name: Release

on:
  push:
    branches: [ "master" ]

permissions: write-all

jobs:

  build-and-deploy:
    uses: 'OpenDonationAssistant/oda-k3s-specs/.github/workflows/release_service.yml@main'
    secrets: inherit
    with:
      service: donationgoal-service
      version: '${{ github.RUN_NUMBER }}'
      npm: false
